
services:

  db:
    image: postgres:16
    container_name: supportdesk_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine

  rabbitmq:
    image: rabbitmq:3-management
    container_name: supportdesk_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: .
    container_name: supportdesk_web
    env_file: .env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    command: >
      sh -c "python manage.py migrate_schemas --shared &&
             python manage.py migrate_schemas &&
             python manage.py runserver 0.0.0.0:8000"

  celery_worker:
    build: .
    container_name: supportdesk_celery_worker
    env_file: .env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    command: celery -A SupportDesk worker --loglevel=info

  celery_beat:
    build: .
    container_name: supportdesk_celery_beat
    env_file: .env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    command: celery -A SupportDesk beat --loglevel=info

volumes:
  postgres_data:
